changelog:
  sections:
    - title: ":new: New Features"
      labels: [ "new feature" ]
    - title: ":warning: Breaking Changes"
      labels: ["breaking change"]
    - title: ":star: Enhancements"
      labels: ["enhancement"]
    - title: ":package: Dependency Upgrades"
      labels: ["dependencies"]
    - title: ":beetle: Bug Fixes"
      labels: ["bug"]
    - title: ":test_tube: Tests"
      labels: ["test"]