changelog:
  sections:
    - title: "Breaking Changes"
      emoji: ":warning:"
      labels: ["breaking change"]
    - title: "Enhancements"
      emoji: ":star:"
      labels: ["enhancement"]
    - title: "Dependency Upgrades"
      emoji: ":package:"
      labels: ["dependencies"]
    - title: "Bugs"
      emoji: ":beetle:"
      labels: ["bug"]