changelog:
  sections:
    - title: ":warning: Breaking Changes"
      labels: ["breaking change"]
    - title: ":star: Enhancements"
      labels: ["enhancement"]
    - title: ":package: Dependency Upgrades"
      labels: ["dependencies"]
    - title: ":beetle: Bugs"
      labels: ["bug"]