# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

requirements_file: requirements.txt

python:
  version: 3.8.3

# Build configuration
build:
  image: latest
  configuration: conf.py

# Setup submodules
submodules:
  include: all

# Configuration spécifique à Sphinx
sphinx:
  configuration: conf.py

